### ISSUE TITLE
OnAppOpenAttribution Issue

### ISSUE THREAD

**Issue by raghibkhan** [AppsFlyerSDK/appsflyer-unity-plugin#57] opened 2021-02-02 12:41 UTC
OnAppOpenAttribution method is still not being called if the app is in kill state. If the app is open or it is in foreground state, this method gets called though. Because of this, the OneLink feature is broken.

**Comment by wesfieldj** [comment] 2021-02-02 15:05
Hi @raghibkhan thanks for reporting this issue.

We are aware of the problem and this will be fixed in the next release. 

Thanks!

**Comment by aaaverin** [comment] 2021-02-04 17:49
As I understand it, now onAppOpenAttribution is called immediately after didFinishLaunching inside the sdk. In this case, the call goes to an object named AppsFlyerObject even before the sdk is initialized. The object that we pass to initialization has no value. If the object is not found, we see the error <Notice>: SendMessage: object AppsFlyerObject not found!. That is, if we make an object immediately in the first scene that can accept the corresponding messages, then we can catch onAppOpenAttribution. Or am I wrong?

**Comment by katan99** [comment] 2021-02-08 13:14
Can you tell me in which version of the SDK this problem first appeared?

**Comment by wesfieldj** [comment] 2021-02-15 16:14
@raghibkhan @aaaverin 

The issue is fixed in v6.2.0 for all links that are not short OneLinks.

<hr/>

The fix for OneLinks needs to be done on the iOS SDK side, which will take some more time until we can get it out. 

However, for a temporary fix, you can add the following line of code:

`[AppsFlyerLib shared].appsFlyerDevKey = @"dev_key_here";`

in AppsFlyerAppController [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyerAppController.mm#L56).

Adding this line of code (with v6.2.0) will solve the issue for all links. 
And in the near future when we fix the issue on the SDK side, adding this line of code will not be necessary.

**Comment by GSRicky** [comment] 2021-02-18 01:56
@wesfieldj

We attempted the dev key workaround on iOS (SDK 6.2.0, Unity 2018.2.21f1, Xcode 11.3.1) but there was no change in behavior. Our OneLinks are still not working on iOS when the app is in the killed state; clicking the OneLink opens the app but onAppOpenAttribution is not called. In all other cases on iOS and Android, the OneLinks are working as expected.

We confirmed in Xcode that the AppsFlyerAppController.mm modification is present after the Unity build. 
Tested on iOS 13.5.1 and iOS 12.3.1.

**Comment by IgorGalimski** [comment] 2021-02-26 13:56
Hi!
@wesfieldj 
We have the same issue on iOS 13.3.1, 13.5.1, 12.1.1, Don't have on iOS 14.5 beta
A link is generated via web and onInviteLinkGenerated method. Both links don't work
Do you have ETA to fix it?
Thanks!

**Comment by btmorgan** [comment] 2021-03-26 19:38
@wesfieldj is there any update on this issue? Like both @GSRicky and @IgorGalimski, we have tried the recommended dev key workaround and continue to see the issue as it is described above: 

Clicking a OneLink with our application already running in the background results in IAppsFlyerConversionData.onAppOpenAttribution being invoked as expected. However, when clicking a OneLink that launches our application from a cold/killed state, IAppsFlyerConversionData.onAppOpenAttribution is not invoked.

We are currently using the following versions:
Unity 2019.4.13f
AF v6.2.41
XCode 12.2

This is a critical issue for us so any guidance on when we may see a fix or a recommended stable version that we could roll back to would be appreciated.

Thanks!

**Comment by IgorGalimski** [comment] 2021-03-30 09:29
Hi, @btmorgan !
Do you use this
[https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md](swizzling)

And what other 3d party do you have in your project?

**Comment by btmorgan** [comment] 2021-03-30 17:20
> 
> 
> Hi, @btmorgan !
> Do you use this
> [https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md](swizzling)
> 
> And what other 3d party do you have in your project?

We did follow that swizzling guide in order to resolve an issue with the Facebook SDK not returning to our application after processing a login (https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/47). 

The other relevant plugins we use are as follows:

Facebook 
Firebase Crashalytics
Firebase Messaging

Have you been able to resolve this in your own project? Incompatibilities between certain plugins has been an issue we have frequently encountered in the past and such issues are usually not straightforward to resolve. Any suggestions you may have would be appreciated!

**Comment by butellab** [comment] 2021-03-31 11:53
AppsFlyer version: 6.2.41
Unity: 2019.4.4f1
OS: iOS
 - Custom UnityAppDelegate, but source logic AppsFlyer saved (all works well, except for the direct deeplink from the cold app open)

I can confirm that I have exactly the same situation as described by @aaaverin. [App not open (kill state, cold open) => Click to deeplink => App opens => No callbacks about open deeplink]

I have set up the logs and I see that the calls (unityCallback) go to nothing (before init, startSdk and etc.). I also observe a duplication of calls.
@wesfieldj 

If you look at previous versions, the problem was there a long time ago (I am new to using appsflyer)? @aaaverin @IgorGalimski @btmorgan 

I might be wrong :/

**Comment by IgorGalimski** [comment] 2021-03-31 12:03
> > Hi, @btmorgan !
> > Do you use this
> > [https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md](swizzling)
> > And what other 3d party do you have in your project?
> 
> We did follow that swizzling guide in order to resolve an issue with the Facebook SDK not returning to our application after processing a login (#47).
> 
> The other relevant plugins we use are as follows:
> 
> Facebook
> Firebase Crashalytics
> Firebase Messaging
> 
> Have you been able to resolve this in your own project? Incompatibilities between certain plugins has been an issue we have frequently encountered in the past and such issues are usually not straightforward to resolve. Any suggestions you may have would be appreciated!

Hi!
I found a possible reason - incorrect GO callback name. Support is investigating this issue now

**Comment by IgorGalimski** [comment] 2021-03-31 12:04
> AppsFlyer version: 6.2.41
> Unity: 2019.4.4f1
> OS: iOS
> 
> * Custom UnityAppDelegate, but source logic AppsFlyer saved (all works well, except for the direct deeplink from the cold app open)
> 
> I can confirm that I have exactly the same situation as described by @aaaverin. [App not open (kill state, cold open) => Click to deeplink => App opens => No callbacks about open deeplink]
> 
> I have set up the logs and I see that the calls (unityCallback) go to nothing (before init, startSdk and etc.). I also observe a duplication of calls.
> @wesfieldj
> 
> If you look at previous versions, the problem was there a long time ago (I am new to using appsflyer)? @aaaverin @IgorGalimski @btmorgan
> 
> * The devkey installation fix directly in the source code did not help. As far as I know this fix was found from AppsFlyer React Sdk and that's another story.
> 
> I might be wrong :/

Hi!
I found a possible reason - incorrect GO callback name. Support is investigating this issue now

**Comment by butellab** [comment] 2021-03-31 12:12
> Hi!
> I found a possible reason - incorrect GO callback name. Support is investigating this issue now

According to my observations, it's not about the name or the wrong actions. The point is that **everything is done and called Before the init, startSdk, the creation of the sdk object**.

**Comment by btmorgan** [comment] 2021-03-31 16:31
> 
> 
> > Hi!
> > I found a possible reason - incorrect GO callback name. Support is investigating this issue now
> 
> According to my observations, it's not about the name or the wrong actions. The point is that **everything is done and called Before the init, startSdk, the creation of the sdk object**.

We have taken a closer look at the inner workings of the plugin code and have come to the same conclusion. The attribution functionality is being processed internally by the plugin before the AppsFlyer.initSDK method is invoked by our application code. In such cases, the onAppOpenAttribution method is never invoked on the IAppsFlyerConversionData object we pass to that initSDK method. This was not an issue on v5.xx, which is what we are in the process of upgrading from.

I'm hoping that this can be resolved in one of the following ways:

1.) Always keep a cached copy of the attribution data string whenever a OneLink is processed. In cases where this string has been assigned a value before AppsFlyer.initSDK is called, immediately invoke the onAppOpenAttribution method in response to that initSDK call. Generally, I believe that this is how v5.xx of the plugin worked to solve for this race condition. 

2.) Always keep a cached copy of the attribution data string whenever a OneLink is processed and publicly expose it via an  accessor. This will allow it to be queried and used externally in cases where it has been assigned before the AppsFlyer.initSDK method is called.

It is worth noting that we don't call the AppsFlyer.initSDK directly from the Start() method of our applications first loaded scene. I'm hoping that this will not become a requirement as it gives us the flexibility to write our own application initialization logic without having to worry about a race condition between initializing a plugin and that plugins own inner workings. However, if this is deemed a requirement, it would be helpful to update the integration documentation to explicitly call this out.

**Comment by pazlavi** [comment] 2021-03-31 16:36
@IgorGalimski  thank you for the info you shared with us. 

Indeed the `onAppOpenAttribution`​ is been called before the C# is initialized.  
As a workaround please follows these steps: 
Please open our SDK files and add the next 
`[AppsFlyerLib shared].appsFlyerDevKey = @"dev_key_here"; // replace dev_key_here with the dev key  
`in AppsFlyerAppController [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyerAppController.mm#L57).
Also, add the same line to AppsFlyer+AppController.m [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L54) **if you are using our Swizzling option.**

If your game object name **is not**  `AppsFlyerObject ` do also the next steps: 
1- open the file AppsFlyeriOSWrapper.h
2- change the value of the parameter [ConversionDataCallbackObject](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyeriOSWrapper.h#L25)​ (line 25) to the name of your game object that contains the IAppsFlyerConversionData​ implementation. (AppsFlyer in your sample project)

**Comment by IgorGalimski** [comment] 2021-04-22 07:43
@pazlavi 
Hi
Was you able to manage the issue?

**Comment by PHARTGAMES** [comment] 2021-05-26 07:07
On iOS 14.5.1 with sdk 6.3.0 I tried both the default sdk and the workaround from pazlavi and I still get no onAppOpenAttribution callback.
I have also tried 6.2.63 both with and without the workaround.

I also get no callback for OnDeepLinkReceived when trying to use that also.

Prior to turning on isDebug I would I get an onConversionDataSuccess every start with a small number of properties, however after turning on isDebug I get the custom properties data in that dictionary from my deeplink.... Even after turning off isDebug I still get all these extra properties.. maybe unrelated but weird.. Is this expected behaviour? Is it because I have my phone set as a test device?

Besides this I have no problems on android, everything works.

**Comment by IgorGalimski** [comment] 2021-05-27 15:24
@PHARTGAMES 
Try this
- (void)onAppOpenAttribution:(NSDictionary *)attributionData {
    if(AppsFlyeriOSWarpper.didCallStart){
        unityCallBack(ConversionDataCallbackObject, OAOA_CALLBACK, stringFromdictionary(attributionData));
    }
    else{
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 10 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
            unityCallBack(ConversionDataCallbackObject, OAOA_CALLBACK, stringFromdictionary(attributionData));
        });
    }
}

Instead of existing method - (void)onAppOpenAttribution:(NSDictionary *)attributionData { in Assets/AppsFlyer/Plugins/iOS/AppsFlyeriOSWrapper.mm

**Comment by AiFuYou** [comment] 2021-07-08 12:00
@wesfieldj 
I have the same problem.
Unity 2019.2.21f
AF v6.2.6
XCode 12.5
What to do to deal with it?

**Comment by af-margot** [comment] 2021-07-08 12:56
Hi @AiFuYou,

Could you do the following test and send the result to our [support team](support@appsflyer.com), they will be able to help you! 
- update to the latest version `6.3.2`
- enable debug log
- Deep-link into the app (notice that the app must be open directly from the link in order to get OnAppOpenAttributoin callback)
- send the logs our support.

**Comment by af-margot** [comment] 2022-05-25 12:30
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!

**Closed by af-margot** 2022-05-25 12:30 UTC
