### ISSUE TITLE
Problem With v6.0.1 - beta

### ISSUE THREAD

**Issue by osamaraza24** [AppsFlyerSDK/appsflyer-unity-plugin#37] opened 2020-09-02 15:59 UTC
I'm using xcode Version 12.0 beta 6 (12A8189n) and pod version 1.9.3, there are two errors happens now 
1) AppsFlyeriOSWrapper.mm:60:31: Property 'deviceLoggingDisabled' not found on object of type 'AppsFlyerLib *'
2)AppsFlyeriOSWrapper.mm:92:32: No visible @interface for 'AppsFlyerLib' declares the selector 'logLocationEvent:latitude:' 
it was perfectly working yesterday , i updated the ironsource it requires to update pod then i update pod then this happen my pod version is 1.9.3 ,and when pod install its download Installing Beta-AppsFlyerFramework (6.0.2.174) is this the issue ?

**Comment by RobertBateman** [comment] 2020-09-02 17:38
Hi osamaraza24, 

I had exactly the same problem today. I fixed it by specifiying an exact verison of the Beta-AppsFlyerFramework iOSPod in Assets/AppsFlyer/Editor/AppsFlyerDependancies.xml.

Change line 14 from:
    <iosPod name="Beta-AppsFlyerFramework" version="~> 6.0.1" minTargetSdk="8.0">
To:
    <iosPod name="Beta-AppsFlyerFramework" version="6.0.1.168" minTargetSdk="8.0">

 That way it won't download 6.0.2.174, which looks to be incompatible with the current Unity plugin.

**Comment by osamaraza24** [comment] 2020-09-02 19:02
@RobertBateman Thanks It worked for me

**Comment by wesfieldj** [comment] 2020-09-07 11:09
Hi @osamaraza24 

The issue will be fixed with the release of v6.0.3.

Please note, that due to the last Apple announcement of delaying ATT Authorization pop-up we made a few changes in the SDK so be sure to use the latest version (6.0.3) when released later this week.

As the problem is the latest release, I am closing the issue. Thank everybody for your feedback and collaboration!

**Closed by wesfieldj** 2020-09-07 11:09 UTC
