### ISSUE TITLE
Appsflyer on iOS prevents from others to receive the openUrl notifications

### ISSUE THREAD

**Issue by ssh-pm** [AppsFlyerSDK/appsflyer-unity-plugin#47] opened 2020-10-22 21:02 UTC
AppsFlyerAppController.mm has the following code which restricts from others to receive the openUrl notifications
```
-(BOOL) application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *)options {
    NSLog(@"got openUrl: %@",url);\n
    [[AppsFlyerLib shared] handleOpenUrl:url options:options];\n
    return YES;
}
```
the probable fix would be to call the superclass method so that others who registered for the notification can also receive it

```
-(BOOL) application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *)options {
    NSLog(@"got openUrl: %@",url);
    [super application:application openURL:url options:options];
    [[AppsFlyerLib shared] handleOpenUrl:url options:options];
    return YES;
}
```

**Comment by wesfieldj** [comment] 2020-10-23 08:06
Hi please see #43.

In the latest version, you can enable swizzling which will solve this issue. 
https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md

Calling super is not a good solution for us because it can lead to other issues.

**Comment by ssh-pm** [comment] 2020-10-23 15:50
It still doesn't work perhaps you should add to your guide to comment the IMPL_APP_CONTROLLER_SUBCLASS from AppsFlyerAppController if swizzling is enabled

**Comment by legoritma** [comment] 2020-10-27 11:05
Same here. Updated to v6.0.7 and enabled swizzling still Facebook view is not closing

**Comment by bmgoncu** [comment] 2020-10-27 13:31
Updated to V6.0.7 and did the swizzle guide as instructed on a previous issue.
I have checked device logs and confirmed  the exsistence of it working (log => "swizzled applicationDidBecomeActive")
But the issue **still persists**.
**Test Case**
1. Login with Facebook SDK 
2. Choose "Use Facebook app"
3. Login and return automatically.

instead of closing the browser view  and passing the auth info, it does nothing

**Comment by lexscite** [comment] 2020-11-03 11:29
The problem is definitely related to iOS version. I've tested on two devices. The issue persist only on iPhone XR 14.1. iPhone 6 12.4.6 working fine.

**Comment by sp-jordi-vilalta** [comment] 2020-11-10 22:00
The issue is that openURL returns `YES` unconditionally, meaning the AppsFlyer SDK could handle all the URLs and there's no need to try with any other delegate.
There's a fix in https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/pull/48

**Comment by MartinGonzalez** [comment] 2020-12-01 14:58
Well this is happening with continueUserActivity.
I just tested with swizzling and appsflyer is handling a dynamic link from firebase and do not delegate it to others.

I've replaced this
```
BOOL __swizzled_continueUserActivity(id self, SEL _cmd, UIApplication* application, NSUserActivity* userActivity, void (^restorationHandler)(NSArray*)) {
    NSLog(@"swizzled continueUserActivity");
    [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
    
    if(__original_continueUserActivity_Imp){
        return ((BOOL(*)(id, SEL, UIApplication*, NSUserActivity*))__original_continueUserActivity_Imp)(self, _cmd, application, userActivity);
    }
    
    return YES;
}
```

with this
```
BOOL __swizzled_continueUserActivity(id self, SEL _cmd, UIApplication* application, NSUserActivity* userActivity, void (^restorationHandler)(NSArray*)) {
    NSLog(@"swizzled continueUserActivity");
    [[AppsFlyerLib shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
    
    if(__original_continueUserActivity_Imp){
        return ((BOOL(*)(id, SEL, UIApplication*, NSUserActivity*))__original_continueUserActivity_Imp)(self, _cmd, application, userActivity);
    }
    
       return ((BOOL(*)(id, SEL, UIApplication*, NSUserActivity*))__original_continueUserActivity_Imp)(self, _cmd, application, userActivity)
}
```
And my firebase dynamic link worked (I'n not an iOS dev)
I know about the plugins collisions, but I don't know how swizzling is fixing this

**Comment by ramybenaroya** [comment] 2020-12-08 10:10
@sp-jordi-vilalta Is this issue still relevant after https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/issues/47 merge?

**Comment by wejaikao** [comment] 2020-12-09 06:48
the latest release ( change openURL's return to NO) is not work.
After IMPL_APP_CONTROLLER_SUBCLASS(AppsFlyerAppController) at AppsFlyerAppController.mm,
UnityAppController will not handle AppDelegate anymore. it is a hijack.
there are three way to trigger AppsFlyer's openURL.
1. IMPL_APP_CONTROLLER_SUBCLASS
2. UnityRegisterAppDelegateListener (Facebook use it)
3. __original_applicationDidBecomeActive_Imp (Swizzle)

Is Method 1 necessary ?


> The issue is that `openURL` returns `YES` unconditionally, meaning the AppsFlyer SDK could handle all the URLs and there's no need to try with any other delegate.
> There's a fix in #48

**Comment by sp-jordi-vilalta** [comment] 2020-12-10 17:15
> @sp-jordi-vilalta, @wesfieldj Is this issue still relevant after #47 merge?

The change from #48 fixed the Facebook Login issue for us (#43), but we're using a custom AppController. I guess the end result will depend on the setup of each app. We just checked openURL, I don't know if other delegates may be affected as well.

**Comment by wesfieldj** [comment] 2020-12-14 13:31
@sp-jordi-vilalta @wejaikao @ramybenaroya 
 I was not able to reproduce the issue after the fix, but each app is different and it is difficult to cover all scenarios in this case. 

When swizzling `IMPL_APP_CONTROLLER_SUBCLASS(AppsFlyerAppController)` should be commented out.
We added that to the docs.

We are open to other suggestions on how to solve this globally for those who are still facing the issue.

If the issue is app related (like a custom AppController) then the solution just may need to be per app fix based on the integration.

**Comment by MartinGonzalez** [comment] 2020-12-15 15:29
```
When swizzling IMPL_APP_CONTROLLER_SUBCLASS(AppsFlyerAppController) should be commented out.
We added that to the docs.
```

Where is that doc? This info should be put on a yellow warning box because it's important.
Can you please send me the link of the docs? I couldn't find this on the repo or appsflyer unity integration page

**Comment by wejaikao** [comment] 2020-12-16 02:49
IMPL_APP_CONTROLLER_SUBCLASS is a method that will take a class as parameter, subclasses it from UnityAppController and make it the new AppControlller being called by Unity3D as entry point.

But AppsFlyer is a third-party sdk, not a project framework. It should not grabs whole UnityAppController's duty.

I suggest to comment it by default, and remind developer in the doc.

**Comment by MartinGonzalez** [comment] 2021-02-01 20:40
So this keeps going. I don't have deeplink since i updated appsflyer
@wejaikao did you find a workaround?

**Comment by kklocek-gamesture** [comment] 2021-02-09 14:10
@wesfieldj 

I have similar problem. I've enabled swizzling in our project. SDK works fine overall, but we have a problem with deep links, when user runs installed app via deep link.
I captured logs, and I think that Firebase "catched" that link, and information never goes to the AppsFlyer via OnOpenUrl.

Maybe this would help with that problem, I don't have any workaround at this moment.

**Comment by MartinGonzalez** [comment] 2021-02-09 21:28
> @wesfieldj
> 
> I have similar problem. I've enabled swizzling in our project. SDK works fine overall, but we have a problem with deep links, when user runs installed app via deep link.
> I captured logs, and I think that Firebase "catched" that link, and information never goes to the AppsFlyer via OnOpenUrl.
> 
> Maybe this would help with that problem, I don't have any workaround at this moment.

I had to comment the line in AppslfyerController.mm where uses IMPL_APP_CONTROLLER_SUBCLASS.

**Comment by kklocek-gamesture** [comment] 2021-02-10 07:42
@MartinGonzalez 
I did it and it didn't help with that case.

**Comment by MartinGonzalez** [comment] 2021-02-10 11:25
@kklocek-gamesture did you tried this?

https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md

**Comment by nodrock** [comment] 2021-03-17 11:17
I have similar problem and I thing that AppsFlyerSDK should never call IMPL_APP_CONTROLLER_SUBCLASS. It should be sufficient to use AppDelegateListener with UnityRegisterAppDelegateListener. Could someone from AppsFlyer tell us why you need call to that macro? (Maybe you need that for swizzling but calling that macro will also replace default entry point for app as @wejaikao mentioned in his comment)

**Comment by kklocek-gamesture** [comment] 2021-03-17 11:27
I'm really sorry for not providing updates.
I read the Swizzling Guide, I've commented out
IMPL_APP_CONTROLLER_SUBCLASS, and my case simply don't work. On device I
saw that deepling was "caught" by Firebase Analytics and prompt that link
is wrong, however I don't use Firebase deep links nor its configuration o0 .

Currently I'm working on upgrading app to newest version of plugin and if
it would work I'll write here.

śr., 17 mar 2021 o 12:18 Jan Horvath ***@***.***> napisał(a):

**Comment by nodrock** [comment] 2021-03-17 11:39
Actually I think that you should also call UnityRegisterLifeCycleListener in the same place where you call UnityRegisterAppDelegateListener and that should cover all your problem. And of course init that class in load method.

**Comment by kklocek-gamesture** [comment] 2021-03-17 11:47
Thanks for you answer Jan! Will try. Now I see that in new version contains
new logic, so I will tset it first.

śr., 17 mar 2021 o 12:39 Jan Horvath ***@***.***> napisał(a):

**Comment by kklocek-gamesture** [comment] 2021-03-18 09:30
@wesfieldj I have a question related to https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md

So, I've enabled swizzling, and mostly deep link works. But on iOS 14.4 it doesn't collect IDFA.
I've disabled swizzling and IDFA collecting works.

I have one question regarded to swizzling guide:
`Validate that the code in the AppsFlyer+AppController is called on the native side.` - how can I do it? Sorry if it's simple question, but I'm not iOS developer :< .

Also in AppsFlyerAppController there are information with:
1. ```/**
 Note if you would like to use method swizzeling see AppsFlyer+AppController.m
 If you are using swizzeling then comment out the method that is being swizzeled in AppsFlyerAppController.mm
 Only use swizzeling if there are conflicts with other plugins that needs to be resolved.
*/``` - so I have to comment out methods in AppsFlyerAppController? I did it, but I think that AF doesn't work
2. There is also note: ```Note if you would not like to use IMPL_APP_CONTROLLER_SUBCLASS you can replace it with the code below.```. Do I have to do this also?
I'm using plugin version 6.1.4.

**Comment by nodrock** [comment] 2021-03-24 09:27
@kklocek-gamesture I tested many variations and the reason why AppsFlyer used IMPL_APP_CONTROLLER_SUBCLASS is primary because they need access to application:continueUserActivity: If you use swizzeling then it should be safe to remove IMPL_APP_CONTROLLER_SUBCLASS but I think it should not be necessary. Buy it would be better if someone from AppsFlyer could confirm this.

**Comment by kklocek-gamesture** [comment] 2021-03-30 08:35
@nodrock Will definitely try it!
Thanks!

**Comment by s-sixteen** [comment] 2022-02-03 22:15
From looking at the code, it seems that AppsFlyer could use UnityRegisterAppDelegateListener to handle all of its notification needs. But, when you comment out `IMPL_APP_CONTROLLER_SUBCLASS`, AF will no longer receive the `continueUserActivity` callback, which is apparently used to handle OneLink deep links.

Thus, for a simple fix for gamedevs using Firebase, Facebook and AppsFlyer SDKs, I suggest commenting out `IMPL_APP_CONTROLLER_SUBCLASS` and calling `swizzleContinueUserActivity` in AppsFlyer+AppController.m

**Comment by af-margot** [comment] 2022-05-25 12:28
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version
Please reopen if you still encounter this issue :) 

Thank you!

**Closed by af-margot** 2022-05-25 12:28 UTC
