### ISSUE TITLE
[Unity - iOS] Facebook Login cannot complete with present of AppsFlyerSDK

### ISSUE THREAD

**Issue by amaluca** [AppsFlyerSDK/appsflyer-unity-plugin#43] opened 2020-10-08 05:43 UTC
[Condition]
Facebook SDK for Unity `v8.0.0`
AppsFlyer SDK for Unity `v6.0.3`
Unity 2019.4.6f1
iOS device (tested on iOS 14.0.1)

[Step to reproduce]
1. Create a unity project
2. Import and setup Facebook SDK for login
3. Import AppsFlyer SDK
4. Build project and run on iOS device
5. Do the login with Facebook. The main app will enter background mode, Facebook app appears.
6. After the login, the main app returns to foreground and sticks there because Facebook login pop up does not close.
* The behavior is similar to [this clip](https://vimeo.com/363750907). (This clip not mine. I get it on internet) 

[Temporary Fix]
Facebook SDK works normally when I:
Option 1: Remove AppsFlyer SDK
Option 2: Downgrade to AppsFlyer SDK `v5.4.2`

**Comment by wesfieldj** [comment] 2020-10-08 06:07
Hi @amaluca,

Thanks for providing us with all those details.

The issue is likely caused by a conflict with the AppsFlyer & FB SDK's in the [openURL](https://developer.apple.com/documentation/uikit/uiapplication/1648685-openurl?language=objc) method.

If this is indeed the issue, then there are a few ways to solve this:

1.  Comment out the openURL method in the [AppsFlyerAppController](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyerAppController.mm#L66) class, and if you are using AppsFlyer for deeplinking as well, then make sure to merge the code inside openURL with the openURL method in the Facebook SDK.
2. Use the swizzeled method in [AppsFlyer+AppController.m](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/Assets/AppsFlyer/Plugins/iOS/AppsFlyer%2BAppController.m#L46). You will need to comment out the original openURL method and use the swizzled method instead. 

We are aware these are workarounds and we will look into providing a better solution in the future. 


If commenting out the openURL method does not solve the issue, then let us know and we can investigate further.

Finally, the reason downgrading solved the issue is because we had a bug in the earlier versions with the openURL method which was solved in v6.0.3.


Thanks!

**Comment by amaluca** [comment] 2020-10-09 06:19
Hi @wesfieldj
Thanks for your rely. I successfully login Facebook with solution 1 (comment out the openURL method in AppsFlyerAppController class). Second solution 2 takes me to other headache of missing header files.
Solution 1 is enough for me. Thank you very much.

**Comment by ehidna** [comment] 2020-10-14 11:20
@wesfieldj commenting out the openURL method solved our issue too but i couldn't merge openurl method codes into facebooksdk.
What will happen if i leave it that way?

**Comment by shniqq** [comment] 2020-10-14 15:19
@wesfieldj we are also facing this issue, and simply downgrading the SDK or commenting out code does not seem like a proper solution (as you also seem to be aware of).
Is there any ETA for an updated SDK version from your side?

**Comment by wesfieldj** [comment] 2020-10-14 19:18
@chebedzic I will release an update of the plugin tomorrow (15/10) with the AppsFlyerTracker fix in the swizzled class.
 I was able to reproduce the issue, so we will fix it asap.

I will also add instructions on how to swizzle.

**Comment by wesfieldj** [comment] 2020-10-14 19:20
@ehidna if you are using URL Schemes for deep linking you should use the swizzled solution.

If not you can leave openURL in the appsflyer-controller commented out.

**Comment by ehidna** [comment] 2020-10-14 19:34
> @ehidna if you are using URL Schemes for deep linking you should use the swizzled solution.
> 
> If not you can leave openURL in the appsflyer-controller commented out.
Thank you for your response.

We are not using any deep linking so no problem.

**Comment by wesfieldj** [comment] 2020-10-15 14:14
> @wesfieldj the second method cant be used if im not mistaken, if im please help me:), since when i uncomment the code you provided it requires me to uncomment method on the bottom of the page called __swizzled_openURL, which then says that AppsFlyerTracker is undeclared and i cant import it from anywhere, since i think the name was changed to AppsFlyerLib, but even after changing the name i still get some errors. can you please point me in the right direction?

#45 Fixes the swizzled class.

**Comment by wesfieldj** [comment] 2020-10-15 14:16
@shniqq we are working on a fix for this. We will try to have something out by the end of next week. (22/10)

**Comment by wesfieldj** [comment] 2020-10-22 15:52
@shniqq We released v6.0.7 #46 with an option to swizzle automatically by adding a flag in the info.plist. 

Check out the doc on how this can be done [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/iOS-Swizzling-Guide.md).

**Closed by wesfieldj** 2020-10-22 15:52 UTC
